group = org.purpurmc.purpur

mcVersion = 26.2
apiVersion = 26.2
channel=EXPERIMENTAL
paperCommit = 296037944d74daa4976ddabbbde4e332d932acdc

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs=-Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=60
